/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Edgar Albedi
 * Created: 18 may. 2023
 */

INSERT INTO CATEGORY VALUES (1, 'Sports');    
INSERT INTO CATEGORY VALUES (2, 'Finance');    
INSERT INTO CATEGORY VALUES (3, 'Movies');  

INSERT INTO USER_PORTAL VALUES (1, 'edalbedi@gmail.com', '4427889566', 'Pruebas');
INSERT INTO USER_PORTAL VALUES (2, 'albedi@ersoluciones.mx', '4421449566', 'Edgar B');
INSERT INTO USER_PORTAL VALUES (3, 'edalbedi@yahoo.com.mx', '4421448522', 'Albedi');

INSERT INTO USER_PORTAL_CATEGORY VALUES (1,1);
INSERT INTO USER_PORTAL_CATEGORY VALUES (1,2);
INSERT INTO USER_PORTAL_CATEGORY VALUES (1,3);

INSERT INTO USER_PORTAL_CATEGORY VALUES (2,2);
INSERT INTO USER_PORTAL_CATEGORY VALUES (2,3);

INSERT INTO USER_PORTAL_CATEGORY VALUES (3,3);

INSERT INTO CHANNEL VALUES (1,'SMS');
INSERT INTO CHANNEL VALUES (2,'MAIL');
INSERT INTO CHANNEL VALUES (3,'PUSH');

INSERT INTO USER_PORTAL_CHANNEL VALUES (1,1);
INSERT INTO USER_PORTAL_CHANNEL VALUES (1,2);
INSERT INTO USER_PORTAL_CHANNEL VALUES (1,3);

INSERT INTO USER_PORTAL_CHANNEL VALUES (2,2);
INSERT INTO USER_PORTAL_CHANNEL VALUES (2,3);

INSERT INTO USER_PORTAL_CHANNEL VALUES (3,3);
